### ISSUE TITLE
在maptalks升级到0.29版本后会，maptalks.animatemarker会报错

### ISSUE THREAD

**Issue by liubgithub** [maptalks/maptalks.animatemarker#3]
错误见截图
![w esa4ujcl92 tfbji 7f](https://user-images.githubusercontent.com/5208386/30741761-bdfbf4a0-9fc8-11e7-92da-3692d3d53725.jpg)
重现如下：http://139.159.219.234/maptalksdemo/dist/geo_examples/光晕闪烁效果并增加新的点.html

**Comment by fuzhenn** [comment]
已经定位并解决, 0.30.0版发布后会解决该问题
